name: Go CI

on:
  push:
    branches: [ main ]
    paths: [ "goServices/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "goServices/**" ]

jobs:
  test:
    name: go_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Verify modules
        run: |
          go version
          go mod tidy
          go mod download

      # uncomment if your Go code is in the go/ subdir
      - name: Set working directory
        run: echo "WORKDIR set"
        working-directory: goServices

      - name: Run tests
        run: go test ./... -v
        working-directory: goServices   # uncomment if tests live in go/
